### ISSUE TITLE
Hidhide Device tab Not Responding

### ISSUE THREAD

**Issue by ghost** [nefarius/HidHide#109]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://vigem.org/Community-Support/
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Hidhide freezes when going to the device tab. The app wont unfreeze 99% of the time. Once every month, the app unfreezes after 15-30minutes5. Got an update today (may 4th 2023) and had to reinstall ds4 because It broke after forcing a restart. This is unacceptable on a high end pc. There is definitely something wrong with the app.

My specs: i9-12900k
3080 ti
32gb 3600 cl16

### Steps to reproduce
- Start Ds4windows
- Open hidhide
- go to device tab
- app not responding
- force close the program
- repeat from step 1

**Actual result:** Hi, Hidhide freezes when going to the device tab.

**Expected result:** Device tab should not freeze the app and render it unusable.

### Screenshots
![image](https://user-images.githubusercontent.com/130636608/236380896-f8a2fad0-d38d-4d1e-b646-edf59074b484.png)

### Machine info

i9-12900k
Windows 10 pro build 19045
3080ti
32gb ram 3600 cl16
1tb m.2 ssd
**Software/driver version(s):** 1.2.98.0

### Any other helpful information
Happens with DS4, DS5 and DS5 Edge.
The issue has been going on for years now. Having to reinstall everything each week really adds up in the long term.

**Comment by nefarius** [comment]
> This is unacceptable on a high end pc.

Well, bugs typically do not care if a PC is high end or a potato 🤣 

> The issue has been going on for years now. Having to reinstall everything each week really adds up in the long term.

You had years worth of time to file a bug then and chose to accept your fate instead 🙂 HidHide exists for only 2 years in total so that statement is a bit dramatic 😛 

Anyway, have you tried the command line client instead? Does that work? Can it list your devices? Have you followed the debug instructions outlined in the README?

Knowing what hardware you sport is nice and all but without more details about e.g. which HID device it may freeze on etc. this issue won't lead to any solutions in the near future.

**Comment by Watch251** [comment]
I also have a Rog gl503ge which the bug has been happening since hidhide replaced the hide function in DS4.

I did not know about github before creating this account a couple of months ago! Your software Vigem and hidhide were download/updated directly from DS4windows.

- I have not tried the command line client. **Where is it?**
- I have not seen the readme for the hidhide app. **Where is it located?**
- The device tab showing the HID freezes with the Dualshock 4 (v1 and v2), Dualsense 5 and DS5 Edge.
- Changing the usb port in which the controller is plugged in, will make me have to hid the same controller again.
- I have a kb/m combo from 2015. The brand is the one made by bestbuy. MODAL CLAYMORE
![image](https://user-images.githubusercontent.com/130636608/236666134-2520af1e-ed47-4af4-982f-52d7d844c43e.png)

After sometime, I will manage to hide my controller and it will work. But going back to hidhide, will still freeze the app.

**Comment by nefarius** [comment]
> * I have not tried the command line client. **Where is it?**

In the installation directory? Like any software since Windows 95?

> * I have not seen the readme for the hidhide app. **Where is it located?**

It's literally the landing page of the repository, impossible to miss.

**Comment by nefarius** [comment]
Can't reproduce.

**Comment by SSSiyan** [comment]
I have this too, could I get instructions on how to use the command line client? At a total guess I've thrown in HidHideCLI.exe to cmd and was given
Error code 0x0005 at src\FilterDriverProxy.cpp(33) `anonymous-namespace'::Device: Access is denied.

**Comment by nefarius** [comment]
> Error code 0x0005 at src\FilterDriverProxy.cpp(33) `anonymous-namespace'::Device: Access is denied.

You need to close other apps that access HidHide right now. For usage, search the issue tracker, there are examples.

**Comment by nefarius** [comment]
Related #119
