### ISSUE TITLE
Change the icon to look more modern

### ISSUE THREAD

**Issue by RobbyCBennett** [nefarius/HidHide#140]
I remade the existing icon as an SVG. I'm not really sure what it is, but it looks like the black and yellow are a retro game controller and the green is a either a ghost or a forcefield.

SVG with original colors:
<img src="https://github.com/nefarius/HidHide/assets/22121365/f017f7e5-3a63-414e-abcc-2b721f37b1ee" width="200" height="200">

SVG with different colors:
<img src="https://github.com/nefarius/HidHide/assets/22121365/a257dcd9-78e5-45bf-9141-3413b6ece81d" width="200" height="200">

Also, thanks for this great software!

**Comment by nefarius** [comment]
Ha, that one was on my bucket list for a long time, I tried to feed the original icon into A.I. but didn't have the time to make it look good. Thanks for the efforts, it's appreciated. To explain the original idea behind the icon; it was meant to be a joystick covered by a cloak. Since, you know, cloaking your game controllers and all :stuck_out_tongue: 

I think Eric made the initial Icon in the VS Bitmap Editor or Paint IIRC.

**Comment by RobbyCBennett** [comment]
Ah, okay, now it makes sense. Here it is with the neckline fixed to make it look more like a cloak. If you like it, I can easily export it as vector images of different scales and make a .ico file.

<img src="https://github.com/nefarius/HidHide/assets/22121365/391c71ca-3bb5-4495-a4ab-0dd3a3bbad82" width="200" height="200">

<img src="https://github.com/nefarius/HidHide/assets/22121365/f820722f-8f29-403a-a730-198f3e04cb05" width="200" height="200">

**Comment by RobbyCBennett** [comment]
Here's a version where the controller is actually covered by the cloak.

<img src="https://github.com/nefarius/HidHide/assets/22121365/7b66071c-c4eb-44eb-9611-3cfacdd0bde4" width="200" height="200">

<img src="https://github.com/nefarius/HidHide/assets/22121365/6e28b9d8-45a7-4974-91b2-8aa5409eca65" width="200" height="200">

**Comment by nefarius** [comment]
Will already be part of the next release ✨
