### ISSUE TITLE
Xbox/XInput blocking through UI Client broken

### ISSUE THREAD

**Issue by nefarius** [nefarius/HidHide#39]
Reminder to do a test run and pinpoint why apparently Xbox controller (and similar variants) blocking is either not working at all or not reliably.

**Comment by ShiveringLampshade** [comment]
Hi, I'm currently running into this issue with an Xbox 360 controller on Windows 10. The controller is currently selected with device hiding enabled but the game I have tested (Rocket League) is still recognizing it. Happy to provide any further info to aid with the investigation


![xb360](https://user-images.githubusercontent.com/90719241/133310201-dcefa28e-726f-4871-99c5-8c01b2a45502.png)

**Comment by nefarius** [comment]
I know, still broken, haven't had time to look into it ❤️

**Comment by ShiveringLampshade** [comment]
No problem 🙂 In my testing its only the 360 controller having the issue, 1st generation Xbox One controller works perfectly fine with HidHide

**Comment by Serfrost** [comment]
I can also confirm this is happening with my Dualsense (PS5) controller.

**Comment by nefarius** [comment]
It works reliably using the CLI instead as a workaround and not using Beta products like Windows 11 😜💙

**Comment by Serfrost** [comment]
> It works reliably using the CLI instead as a workaround and not using Beta products like Windows 11 😜💙

Maybe you missed my edit. All's good. lol

**Comment by Kanuan** [comment]
IIRC, some Windows update break HidGuardian / HidHide. There were many similar reports from users with Windows 7/8/10 in the past (me included). The solution is just to reinstall the driver.

**Comment by nefarius** [comment]
@Serfrost I didn't miss it, just like the chance to bash Windows 11 😁

**Comment by Serfrost** [comment]
> @Serfrost I didn't miss it, just like the chance to bash Windows 11 😁

Oh. lmao  I should have caught that since it was only a part of the edit.  I have my own grievances with 11, but it's mainly that they took away my ability to move the taskbar to the left / right of the screen.  Broke a lot of my automation.  Assholes.  Other than that I've had a decent time since June.

**Comment by nefarius** [comment]
There is so much wrong with Windows 11. The absolutely avoidable planned obsolescence with their ridiculous hardware requirements (I don't care if workarounds exist, it's about the mentality), forcing TPM which improves literally nothing in regards to exploitability, having changes introduced that break core functionalities without having the documentation updated so nobody has any clue why software breaks that worked flawlessly for every Windows 10 revision etc. and so on and so forth.... It's a dumpster fire for me as a developer.

Rant over 😛

**Comment by Serfrost** [comment]
Yeah, I come from strictly on the user side.  As for ya'll on the dev side of the fence, I can see how it's just getting increasingly worse so long as everything keeps getting thrown under the bus.  Hopefully that changes for the better.

**Comment by imperialmarch55** [comment]
Hi, huge fan of your work and am working on a little input mapper application. I saw your comment that XInput hiding via the CLI was a reliable workaround for XInput devices not being hidden properly, but for me it only seems to work halfway.

So first off I see no difference between using the UI and the CLI, but my problem is that when using Xbox 360 controllers of any kind, only the non-XInput controller is being hidden, but not the XInput one. So for games and emulators that don't accept XInput but use a different API instead, the controller is hidden just fine, but for programs that implement XInput, the XInput device is still visible. This does not happen with any controllers that present themselves as any type of Xbox One controller.

I have quite the controller collection so I've been able to test pretty extensively. So I was just wondering if this was a known issue, or if this was somehow coming from my end. I'll be more than happy to provide any additional information should you need it. And of course, thank you for everything you do, I really appreciate your software and use it all the time.

**Comment by imperialmarch55** [comment]
> It works reliably using the CLI instead as a workaround and not using Beta products like Windows 11 😜💙

Hi, huge fan of your work and am working on a little input mapper application. I saw your comment that XInput hiding via the CLI was a reliable workaround for XInput devices not being hidden properly, but for me it only seems to work halfway.

So first off I see no difference between using the UI and the CLI, but my problem is that when using Xbox 360 controllers of any kind, only the non-XInput controller is being hidden, but not the XInput one. So for games and emulators that don't accept XInput but use a different API instead, the controller is hidden just fine, but for programs that implement XInput, the XInput device is still visible. This does not happen with any controllers that present themselves as any type of Xbox One controller.

I have quite the controller collection so I've been able to test pretty extensively. So I was just wondering if this was a known issue, or if this was somehow coming from my end. I'll be more than happy to provide any additional information should you need it. And of course, thank you for everything you do, I really appreciate your software and use it all the time.

**Comment by nefarius** [comment]
> > Careful! Hiding the **USB** instance **only works for XInput devices!** For your general purpose joystick, pad, wheel etc. you need to block the **HID-Instance**, e.g. `HID\VID_054C&PID_0268...`
> 
> EDIT: I wrote something up originally but didn't realize you could hide the base container device instance path! A very happy day for me as I've been having this issue for a while. So just thought I'd put this here for anyone who didn't know that if you want to hide an XInput device, you need to hide the base container device instance path that starts with USB instead of HID. And apparently this can only be done through the CLI.

That observation is a 100% true and how XInput blocking works. DInput will access the HID device portion you need to block and XInput will skip past that and directly open a handle to the USB device, so in regards to x360/xbone devices you need to block both the HID and the USB instance.

Cheers

**Comment by Dr4goonD3mon** [comment]
Hi, I have 2 Xinput controllers, 1 Xbox One S controller and 1 Xbox 360 Controller, my issue is that when I hide the controllers 3 apps don't work as intendes, the 1st app is RetroArch, when Hiding the Xbox one controller and enabling the virtual Controller, RetroArch see the virtual controller (notification, is shown), but won't get any Input from this Virtual Controller, and the other 2 app are Dolphin And PCSX2 where these 2 show the virtual controller as xinput1 instead of 0, I tried configuring HidHide from The CLI but the Gui version already hide the USB and HID instances, if I unhide the HID the controller is Visible Again so I keep the two instances hiden, I'm on windows 11 21H2 compitation 22000.556

**Comment by Zebrazilla** [comment]
Trying to hide a virtual xbox 360 controller by also hiding the USB instance path, so far no luck. Tried numerous variations. Am I going about hiding the USB instance in a wrong way? Any ideas?
![image](https://user-images.githubusercontent.com/6796156/163669117-b1cc89cf-6931-41f4-9ee3-5913c246cbd4.png)

**Comment by Kuiriel** [comment]
I'm having a similar issue.

Battlefield 2042 can see 'through' HidHide to my VKB joystick. It is reading it as a controller, and thus ignoring the Vjoy stick - (and also ignoring my other VKB stick that I'm trying to combine with Gremlin into that one vjoy stick)

With the CLI and dev-list I can see that I've hidden

HID\VID_231D&PID_0200\6&1bce44cb&0&0000
HID\VID_231D&PID_3201\6&244c6a3b&0&0000
USB\VID_231D&PID_0200\5&3AC4F59B&0&8
USB\VID_231D&PID_3201\5&3AC4F59B&0&7

I have then also hidden:
USB\VID_231D&PID_0200
USB\VID_231D&PID_3201
HID\VID_231D&PID_0200
HID\VID_231D&PID_3201

Forgive me if I typo. So that's both the HID and the USB container, isn't it?

**Comment by Kanuan** [comment]
1. Open HidHide's CLI
    - It's usually located in ` C:\Program Files\Nefarius Software Solutions\HidHide\x64`
1. Open Windows' Device Manager
1. Change the View at the top to "**Devices by Container**"
1. Locate your Xbox controller in the list
1. Select it so it remains highlighted
1. On the top of Device Manager, switch the "View" to "**Devices by CONNECTION**"
1. When the view changes your Xbox controller should still be selected, then expand its sub-items
1. Follow the instructions in the image below then
    - Your Xbox controller will probably be in a different connection "parent" item than the one shown in the image
1. After the changes are saved on HidHide CLI, reconnect the controller
    - REMEMBER to save the changes by pressing `Ctrl + Z` on the CLI screen (a small code should appear) then pressing Enter
    - You MUST reconnect the controller for the changes to be effective

![image](https://user-images.githubusercontent.com/24910442/186417320-501b91ac-ff4a-4ed7-94a6-6cc47ff1e06e.png)

**Comment by Kuiriel** [comment]
Gamepad Tester can't see either of the VKB joysticks to begin with, because they appear to be correctly hidden. If I use joystick gremlin to activate a profile, Gamepad Tester can see the Virtual Joystick appropriately.

Everything already appears as appropriate on HidHide CLI already.

Only thing is I'm not using an xbox controller, I'm using VKB joysticks. Somehow the game can still see through them to ignore the left stick, ignore vjoy, and use just the right stick as a controller. It shouldn't be able to see that at all.

![HidHide](https://user-images.githubusercontent.com/24553989/186420126-6bf238a8-9927-4857-8b57-5614c6a144c0.png)

**Comment by AAide** [comment]
> I can also confirm this is happening with my Dualsense (PS5) controller.
> 
> Edit: Seems this was caused by Windows update / upgrading to Windows 11. Uninstalling HidHide using the installation MSI, rebooting, and then reinstalling the HidHide using the MSI seems to have resolved this problem.

This is help me thanks.

**Comment by eqagunn** [comment]
> > I can also confirm this is happening with my Dualsense (PS5) controller.
> > Edit: Seems this was caused by Windows update / upgrading to Windows 11. Uninstalling HidHide using the installation MSI, rebooting, and then reinstalling the HidHide using the MSI seems to have resolved this problem.
> 
> This is help me thanks.

This sorted my issue with Switch Pro Controller too. HidHide wasn't hiding neither wireless nor wired connection. Reinstalling HidHide made it functional again. Thank you @Serfrost.

**Comment by katatin31** [comment]
Hi! I can't hide the gamepad. I deleted all hidguardian files, checked using "Legacinator.exe". I tried to reinstall hidhide, but to no avail... maybe there is an option to clean the riest or some other method? I have Windows 10 21H2.
